# Generated by Django 6.1 on 2026-08-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('banner', models.ImageField(upload_to='banners/')),
                ('description', models.TextField()),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('done', 'Done')], default='upcoming', max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
