# Generated by Django 6.1 on 2026-08-09 18:30

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='event',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#FFFF00', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='EventSeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('fee', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('all', 'For everyone'), ('students', 'For School and College Students'), ('custom', 'Create Custom Category')], default='students', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.CharField(choices=[('c01', 'Class 1'), ('c02', 'Class 2'), ('c03', 'Class 3'), ('c04', 'Class 4'), ('c05', 'Class 5'), ('c06', 'Class 6'), ('c07', 'Class 7'), ('c08', 'Class 8'), ('c09', 'Class 9'), ('c10', 'Class 10'), ('c11', 'Class 11'), ('c12', 'Class 12'), ('c13', 'This year HSC Batch')], max_length=4)),
                ('end', models.CharField(choices=[('c01', 'Class 1'), ('c02', 'Class 2'), ('c03', 'Class 3'), ('c04', 'Class 4'), ('c05', 'Class 5'), ('c06', 'Class 6'), ('c07', 'Class 7'), ('c08', 'Class 8'), ('c09', 'Class 9'), ('c10', 'Class 10'), ('c11', 'Class 11'), ('c12', 'Class 12'), ('c13', 'This year HSC Batch')], max_length=4)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventseg')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('caref', models.CharField(blank=True, max_length=100)),
                ('trxid', models.CharField(max_length=100, unique=True)),
                ('paymeth', models.CharField(choices=[('bkash', 'Bkash'), ('nagad', 'Nagad'), ('upay', 'Upay')], max_length=10)),
                ('paynum', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('addnote', models.TextField(blank=True)),
                ('participant_class', models.CharField(blank=True, choices=[('c01', 'Class 1'), ('c02', 'Class 2'), ('c03', 'Class 3'), ('c04', 'Class 4'), ('c05', 'Class 5'), ('c06', 'Class 6'), ('c07', 'Class 7'), ('c08', 'Class 8'), ('c09', 'Class 9'), ('c10', 'Class 10'), ('c11', 'Class 11'), ('c12', 'Class 12'), ('c13', 'This year HSC Batch'), ('university', 'University Student'), ('na', 'Not a Student')], max_length=15, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('segment', models.ManyToManyField(to='events.eventseg')),
            ],
        ),
    ]
