# Generated by Django 6.1 on 2026-08-10 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_banner_alter_event_primary_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventseg',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentset', to='events.event'),
        ),
    ]
