# Generated by Django 6.1 on 2026-08-10 19:29

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventseg_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(upload_to=events.models.banner_renamer),
        ),
    ]
