# Generated by Django 6.1 on 2026-09-08 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventseg',
            name='category',
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.CharField(choices=[('c01', 'Class 1'), ('c02', 'Class 2'), ('c03', 'Class 3'), ('c04', 'Class 4'), ('c05', 'Class 5'), ('c06', 'Class 6'), ('c07', 'Class 7'), ('c08', 'Class 8'), ('c09', 'Class 9'), ('c10', 'Class 10'), ('c11', 'Class 11'), ('c12', 'Class 12'), ('c13', 'This year HSC Batch')], max_length=4)),
                ('end', models.CharField(choices=[('c01', 'Class 1'), ('c02', 'Class 2'), ('c03', 'Class 3'), ('c04', 'Class 4'), ('c05', 'Class 5'), ('c06', 'Class 6'), ('c07', 'Class 7'), ('c08', 'Class 8'), ('c09', 'Class 9'), ('c10', 'Class 10'), ('c11', 'Class 11'), ('c12', 'Class 12'), ('c13', 'This year HSC Batch')], max_length=4)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibilities', to='events.event')),
            ],
        ),
        migrations.AddField(
            model_name='eventseg',
            name='eligibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='segments', to='events.eligibility'),
        ),
        migrations.DeleteModel(
            name='ClassRange',
        ),
    ]
