# Generated by Django 6.1 on 2026-09-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_eventseg_category_eligibility_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='Participants',
        ),
    ]
