# Generated by Django 6.1 on 2026-09-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_registration_participants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participants',
            new_name='Participant',
        ),
    ]
