# Generated by Django 6.1 on 2026-09-10 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_participants_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CABatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_open', models.BooleanField(default=False)),
                ('requires_reference', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_batches', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='CampusAmbassador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=100)),
                ('institution', models.CharField(max_length=200)),
                ('class_batch', models.CharField(choices=[('c01', 'Class 1'), ('c02', 'Class 2'), ('c03', 'Class 3'), ('c04', 'Class 4'), ('c05', 'Class 5'), ('c06', 'Class 6'), ('c07', 'Class 7'), ('c08', 'Class 8'), ('c09', 'Class 9'), ('c10', 'Class 10'), ('c11', 'Class 11'), ('c12', 'Class 12'), ('c13', 'This year HSC Batch')], max_length=4)),
                ('address', models.TextField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField(blank=True)),
                ('past_experience', models.TextField(blank=True)),
                ('club_affiliation', models.TextField(blank=True)),
                ('motivation', models.TextField()),
                ('participants_estimate', models.CharField(choices=[('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('40+', '40+')], max_length=3)),
                ('help_plan', models.TextField()),
                ('photo', models.ImageField(upload_to='ca_photos/')),
                ('reference_code', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='events.cabatch')),
            ],
        ),
    ]
