# Generated by Django 6.1 on 2026-09-10 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_cabatch_campusambassador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventseg',
            name='type',
        ),
        migrations.AddField(
            model_name='eventseg',
            name='format',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventseg',
            name='group_label',
            field=models.CharField(blank=True, help_text="Optional heading to cluster related segments on the event page, e.g. 'Singing', 'Quiz Arena'.", max_length=100),
        ),
        migrations.AddField(
            model_name='eventseg',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventseg',
            name='team_size',
            field=models.PositiveIntegerField(blank=True, help_text='Members per team — only meaningful if is_group is True.', null=True),
        ),
        migrations.AlterField(
            model_name='eventseg',
            name='eligibility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='segments', to='events.eligibility'),
            preserve_default=False,
        ),
    ]
