# Generated by Django 6.1 on 2026-09-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_eventseg_type_eventseg_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseg',
            name='subcategories',
            field=models.CharField(blank=True, help_text="Comma-separated styles/options, display only, e.g. 'Patriotic, Folk, Modern/Band'.", max_length=300),
        ),
    ]
