# Generated by Django 6.1 on 2026-09-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_participant_selected_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseg',
            name='icon',
            field=models.CharField(choices=[('music', 'Music / Singing'), ('dance', 'Dance'), ('drama', 'Drama / Acting'), ('art', 'Art / Design'), ('photography', 'Photography'), ('writing', 'Writing'), ('quiz', 'Quiz / Trivia'), ('speech', 'Speech / Debate'), ('comedy', 'Comedy'), ('film', 'Film / Video'), ('tech', 'Tech / Gaming'), ('general', 'General')], default='general', help_text='Subject icon shown on the segment card (chip + background watermark).', max_length=20),
        ),
    ]
