# Generated by Django 6.1 on 2026-09-12 07:16

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_eventseg_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventseg',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Optional custom icon/logo for this specific segment. Overrides the fallback icon above when set.', null=True, upload_to=events.models.segment_icon_renamer),
        ),
        migrations.AlterField(
            model_name='eventseg',
            name='icon',
            field=models.CharField(choices=[('music', 'Music / Singing'), ('dance', 'Dance'), ('drama', 'Drama / Acting'), ('art', 'Art / Design'), ('photography', 'Photography'), ('writing', 'Writing'), ('quiz', 'Quiz / Trivia'), ('speech', 'Speech / Debate'), ('comedy', 'Comedy'), ('film', 'Film / Video'), ('tech', 'Tech / Gaming'), ('general', 'General')], default='general', help_text='Fallback icon shown if no custom icon image (below) is uploaded.', max_length=20),
        ),
    ]
