# Generated by Django 6.1 on 2026-09-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_eventseg_icon_image_alter_eventseg_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='facebook_url',
            field=models.URLField(blank=True, help_text="Link to the event's Facebook page/post, if any."),
        ),
    ]
